export const Estado = [
  { id: 1, key: 'AC', value: 'Acre' },
  { id: 2, key: 'AL', value: 'Alagoas' },
  { id: 3, key: 'AP', value: 'Amapá' },
  { id: 4, key: 'AM', value: 'Amazonas' },
  { id: 5, key: 'BA', value: 'Bahia' },
  { id: 6, key: 'CE', value: 'Ceará' },
  { id: 7, key: 'DF', value: 'Distrito Federal' },
  { id: 8, key: 'ES', value: 'Espírito Santo' },
  { id: 9, key: 'GO', value: 'Goiás' },
  { id: 10, key: 'MA', value: 'Maranhão' },
  { id: 11, key: 'MT', value: 'Mato Grosso' },
  { id: 12, key: 'MS', value: 'Mato Grosso do Sul' },
  { id: 13, key: 'MG', value: 'Minas Gerais' },
  { id: 14, key: 'PA', value: 'Pará' },
  { id: 15, key: 'PB', value: 'Paraíba' },
  { id: 16, key: 'PR', value: 'Paraná' },
  { id: 17, key: 'PE', value: 'Pernambuco' },
  { id: 18, key: 'PI', value: 'Piauí' },
  { id: 19, key: 'RJ', value: 'Rio de Janeiro' },
  { id: 20, key: 'RN', value: 'Rio Grande do Norte' },
  { id: 21, key: 'RS', value: 'Rio Grande do Sul' },
  { id: 22, key: 'RO', value: 'Rondônia' },
  { id: 23, key: 'RR', value: 'Roraima' },
  { id: 24, key: 'SC', value: 'Santa Catarina' },
  { id: 25, key: 'SP', value: 'São Paulo' },
  { id: 26, key: 'SE', value: 'Sergipe' },
  { id: 27, key: 'TO', value: 'Tocantins' },
];
